import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "@/context/theme.context";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/context/tanstack.context";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryClientProvider client={queryClient}>

          <CustomThemeProvider>
            {props.children}
          </CustomThemeProvider>
          {/* TODO: ONly oopen in developemtn mod */}
          <ReactQueryDevtools initialIsOpen={true} />
        </QueryClientProvider>
      </body>
    </html >
  );
}
